/**
 * AUTO-GENERATED by scripts/build-lore-book-references.cjs
 * Maps canon-entity IDs to the static lore-book pages that mention them.
 * Re-run the script after editing any lore book or adding canon entities.
 */

export interface LoreBookRef {
  id: string
  title: string
  subtitle: string
  slug: string
  href: string
  author: string
}

export const LORE_BOOKS: LoreBookRef[] = [
  {
    id: 'lore-narrative-history',
    title: "The Everloop",
    subtitle: "Narrative History",
    slug: 'narrative-history',
    href: '/stories/narrative-history',
    author: "The Lore Codex",
  },
  {
    id: 'lore-four-loops-of-curiosities',
    title: "Four Loops",
    subtitle: "of Curiosities",
    slug: 'four-loops-of-curiosities',
    href: '/stories/four-loops-of-curiosities',
    author: "Archael Viremont",
  },
  {
    id: 'lore-known-wonders',
    title: "Known Wonders",
    subtitle: "of the Everloop",
    slug: 'known-wonders-of-the-everloop',
    href: '/stories/known-wonders-of-the-everloop',
    author: "Archael Viremont",
  },
]

const LORE_BOOKS_BY_SLUG: Record<string, LoreBookRef> = Object.fromEntries(
  LORE_BOOKS.map(b => [b.slug, b])
)

/** entityId -> book slugs that mention it */
const LORE_BOOK_ENTITY_REFS: Record<string, string[]> = {
  '0a29939a-ad32-4c0f-acb9-118a4050bd4f': ['narrative-history', 'known-wonders-of-the-everloop'],
  '7ea48de0-fac8-4523-aa9b-fee895010db5': ['narrative-history', 'known-wonders-of-the-everloop'],
  '681de8c6-fa0e-483f-8a96-e4d03dec0398': ['narrative-history'],
  '85050f7c-bf9a-4d8a-b231-b431bf13d2cd': ['narrative-history', 'four-loops-of-curiosities', 'known-wonders-of-the-everloop'],
  'a7886768-9422-4bce-951f-bb1a5b4b089a': ['narrative-history'],
  '90a3241a-fa02-4fe5-9686-5c2d4f88e88f': ['narrative-history'],
  'd9bb0a5f-048c-491c-bc7c-7e46acb6e53d': ['narrative-history'],
  'ae76de1d-b526-40b7-8f0c-410740afbe98': ['four-loops-of-curiosities', 'known-wonders-of-the-everloop'],
  '9c90779a-8604-4916-ae3e-78daedecce9b': ['four-loops-of-curiosities', 'known-wonders-of-the-everloop'],
  'd6d780a9-f3b6-46f5-875c-18837a3b40fb': ['four-loops-of-curiosities', 'known-wonders-of-the-everloop'],
  '5953693b-cfc9-4b7d-8c64-8f2ad8bb539c': ['four-loops-of-curiosities', 'known-wonders-of-the-everloop'],
  '515afb69-ffe9-441b-af29-ea3dada30c73': ['four-loops-of-curiosities', 'known-wonders-of-the-everloop'],
  '65e8d9b4-3186-4def-b7f7-2dc204c54d48': ['four-loops-of-curiosities', 'known-wonders-of-the-everloop'],
  '93cdbbac-e252-451a-a899-c4303e380be4': ['four-loops-of-curiosities', 'known-wonders-of-the-everloop'],
  '8e1c2b31-6cfd-435e-8a93-b879890a69f3': ['four-loops-of-curiosities', 'known-wonders-of-the-everloop'],
  '9af04060-0622-4e76-8123-7774dc9ff272': ['four-loops-of-curiosities', 'known-wonders-of-the-everloop'],
  '9e48e049-9e0a-4c3b-8219-9d225a5ae330': ['four-loops-of-curiosities', 'known-wonders-of-the-everloop'],
  '8b8dbae5-cf38-419a-9407-cc2247969dfe': ['known-wonders-of-the-everloop'],
  '7b382060-4241-41db-9e4b-32b48f7b8eae': ['known-wonders-of-the-everloop'],
}

/** Return the lore books that reference the given canon entity. */
export function getLoreBooksForEntity(entityId: string): LoreBookRef[] {
  const slugs = LORE_BOOK_ENTITY_REFS[entityId]
  if (!slugs) return []
  return slugs.map(s => LORE_BOOKS_BY_SLUG[s]).filter(Boolean)
}
